hotfolder:
  path: c:\Temp\hotfolder
spring:
    application:
        name: mdm-readings-csv-input
    cloud:
        stream:
            bindings:
                output:
                    destination: mdm-readings-csv-input
                    producer:
                        headerMode: raw
server:
    port: 8081